"use strict";
console.time("challenges took");

var d01 = require("./src/day-01/solver");
var d02 = require("./src/day-02/solver");
var d03 = require("./src/day-03/solver");
var d04 = require("./src/day-04/solver");
var d05 = require("./src/day-05/solver");
var d06 = require("./src/day-06/solver");
var d07 = require("./src/day-07/solver");
var d08 = require("./src/day-08/solver");
var d09 = require("./src/day-09/solver");
var d10 = require("./src/day-10/solver");
var d11 = require("./src/day-11/solver");
var d12 = require("./src/day-12/solver");
var d13 = require("./src/day-13/solver");
var d14 = require("./src/day-14/solver");
var d15 = require("./src/day-15/solver");
var d16 = require("./src/day-16/solver");
var d17 = require("./src/day-17/solver");
var d18 = require("./src/day-18/solver");

console.log("**************ADVENT OF CODE**************");
console.log("  --- Day 1: Not Quite Lisp (1/2) - " + d01.solvePartOne());
console.log("  --- Day 1: Not Quite Lisp (2/2) - " + d01.solvePartTwo());
console.log("  --- Day 2: I Was Told There Would Be No Math (1/2) - " + d02.solvePartOne());
console.log("  --- Day 2: I Was Told There Would Be No Math (2/2) - " + d02.solvePartTwo());
console.log("  --- Day 3: Perfectly Spherical Houses in a Vacuum (1/2) - " + d03.solvePartOne());
console.log("  --- Day 3: Perfectly Spherical Houses in a Vacuum (2/2) - " + d03.solvePartTwo());
console.log("  --- Day 4: The Ideal Stocking Stuffer (1/2) - (disabled b/c slow ~1.5s)"); // + d04.solvePartOne());
console.log("  --- Day 4: The Ideal Stocking Stuffer (2/2) - (disabled b/c slow ~50s)"); // + d04.solvePartTwo());
console.log("  --- Day 5: Doesn't He Have Intern-Elves For This? (1/2) - " + d05.solvePartOne());
console.log("  --- Day 5: Doesn't He Have Intern-Elves For This? (2/2) - " + d05.solvePartTwo());
console.log("  --- Day 6: Probably a Fire Hazard (1/2) - (disabled b/c slow ~1s)"); // + d06.solvePartOne());
console.log("  --- Day 6: Probably a Fire Hazard (2/2) - (disabled b/c slow ~1s)"); // + d06.solvePartTwo());
console.log("  --- Day 7: Some Assembly Required (1/2) - " + d07.solvePartOne());
console.log("  --- Day 7: Some Assembly Required (2/2) - " + d07.solvePartTwo());
console.log("  --- Day 8: Matchsticks (1/2) - " + d08.solvePartOne());
console.log("  --- Day 8: Matchsticks (2/2) - " + d08.solvePartTwo());
console.log("  --- Day 9: All in a Single Night (1/2) - " + d09.solvePartOne());
console.log("  --- Day 9: All in a Single Night (2/2) - " + d09.solvePartTwo());
console.log("  --- Day 10: Elves Look, Elves Say (1/2) - (disabled b/c slow ~1s)"); // + d10.solvePartOne());
console.log("  --- Day 10: Elves Look, Elves Say (2/2) - (disabled b/c slow ~2s)"); // + d10.solvePartTwo());
console.log("  --- Day 11: Corporate Policy (1/2) - " + d11.solvePartOne());
console.log("  --- Day 11: Corporate Policy (2/2) - " + d11.solvePartTwo());
console.log("  --- Day 12: JSAbacusFramework.io (1/2) - " + d12.solvePartOne());
console.log("  --- Day 12: JSAbacusFramework.io (2/2) - " + d12.solvePartTwo());
console.log("  --- Day 13: Knights of the Dinner Table (1/2) - " + d13.solvePartOne());
console.log("  --- Day 13: Knights of the Dinner Table (2/2) - (disabled b/c slow ~2s)"); // + d13.solvePartTwo());
console.log("  --- Day 14: Reindeer Olympics (1/2) - " + d14.solvePartOne());
console.log("  --- Day 14: Reindeer Olympics (2/2) - " + d14.solvePartTwo());
console.log("  --- Day 15: Science for Hungry People (1/2) - " + d15.solvePartOne());
console.log("  --- Day 15: Science for Hungry People (2/2) - " + d15.solvePartTwo());
console.log("  --- Day 16: Aunt Sue (1/2) - " + d16.solvePartOne());
console.log("  --- Day 16: Aunt Sue (2/2) - " + d16.solvePartTwo());
console.log("  --- Day 17: No Such Thing as Too Much (1/2) - (disabled b/c slow ~5s)"); // + d17.solvePartOne());
console.log("  --- Day 17: No Such Thing as Too Much (2/2) - (disabled b/c slow ~5s)"); // + d17.solvePartTwo());
console.log("  --- Day 18: Like a GIF For Your Yard (1/2) -" + d18.solvePartOne());
console.log("  --- Day 18: Like a GIF For Your Yard (2/2) -" + d18.solvePartTwo());

console.timeEnd("challenges took");
